### ISSUE TITLE
Support for .net core  2+

### ISSUE THREAD

**Issue by SergiusZurawski** [devlooped/xunit.assemblyfixture#2]
I might be wrong but it looks like this package doesn't support .net core 2. Is there any plans to provide such support in future?

**Comment by ortrails** [comment]
I managed to port this over to .net core 2. i'll try to work on getting a pull request in here to add multi-targeting to the nuget package, or someone else can do it.
[xunit.assemblyfixture.core.zip](https://github.com/kzu/xunit.assemblyfixture/files/1668498/xunit.assemblyfixture.core.zip)

**Comment by LeaveTheCapital** [comment]
+1 any progress on this?

**Comment by tomaszeman** [comment]
You can use the full-featured implementation of AssemblyFixture from this extension https://github.com/tomaszeman/Xunit.Extensions.Ordering

**Comment by kzu** [comment]
Latest version targets NS2.0
