### ISSUE TITLE
Add support for IMessageSink in the fixtures

### ISSUE THREAD

**Issue by khodaie** [devlooped/xunit.assemblyfixture#3]
Add support for `IMessageSink` as constructor parameter of an assembly fixture class.

The similar work is done in [this commit](https://github.com/xunit/xunit/commit/89d11eca58bed6754304a2b3897bf2a0f6dcd838#diff-d76e354bfac7341ffda4b84391bf9df7)

**Comment by tomaszeman** [comment]
https://github.com/tomaszeman/Xunit.Extensions.Ordering implementation of AssemblyFixture supports IMessageSink injection.

**Comment by kzu** [comment]
ok, CI now properly set up, publishing to nuget.org too, fancy icon and readme and all that stuff.

would you care to send a PR for that feature?

thanks!

**Comment by kzu** [comment]
Closing for now given lack of interest in contributing.
